CREATE TABLE IF NOT EXISTS `wordpress`.`wp_wc_admin_note_actions`(
    `action_id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `note_id` bigint unsigned NOT NULL,
    `name` varchar(255) NOT NULL,
    `label` varchar(255) NOT NULL,
    `query` longtext NOT NULL,
    `status` varchar(255) NOT NULL,
    `actioned_text` varchar(255) NOT NULL,
    `nonce_action` varchar(255) NULL,
    `nonce_name` varchar(255) NULL,
    PRIMARY KEY  (`action_id` ),
    KEY `note_id` (`note_id` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci ;
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (1, 1, 'notify-refund-returns-page', 'Edit page', 'https://comsstore.ynetsolution.com/wp-admin/post.php?post=23&action=edit', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (92, 62, 'connect', 'Connect', '?page=wc-addons&section=helper', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (183, 63, 'visit-the-theme-marketplace', 'Visit the theme marketplace', 'https://woo.com/product-category/themes/?utm_source=inbox&utm_medium=product', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (184, 64, 'day-after-first-product', 'Learn more', 'https://woo.com/document/woocommerce-customizer/?utm_source=inbox&utm_medium=product', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (275, 65, 'learn-more', 'Learn more', 'https://woo.com/mobile/?utm_medium=product', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (906, 66, 'view-payment-gateways', 'Learn more', 'https://woo.com/product-category/woocommerce-extensions/payment-gateways/?utm_medium=product', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (1417, 43, 'woocommerce-WCStripe-May-2023-updated-needed-Plugin-Settings', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (1418, 43, 'woocommerce-WCStripe-May-2023-updated-needed-Plugin-Settings-dismiss', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (1536, 68, 'view-report', 'View report', '?page=wc-admin&path=/analytics/revenue&period=custom&compare=previous_year&after=2024-04-23&before=2024-04-23', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (1596, 44, 'woocommerce-WCPayments-June-2023-updated-needed-Plugin-Settings', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (1597, 44, 'woocommerce-WCPayments-June-2023-updated-needed-Dismiss', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (1612, 53, 'woocommerce-WooPayments-Aug-2023-update-needed', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/update-core.php?', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (1613, 53, 'dismiss', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (2464, 61, 'airwallex_q1_2024', 'Get started with Airwallex', 'https://woocommerce.com/products/airwallexpayments/?utm_source=inbox_note&utm_medium=product&utm_campaign=airwallex_q1_2024', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (6947, 69, 'learn-more', 'Learn more', 'https://woo.com/mobile/?utm_source=inbox&utm_medium=product', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9523, 4, 'learn-more', 'Learn more', 'https://docs.woocommerce.com/document/woocommerce-shipping-and-tax/?utm_source=inbox', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9686, 2, 'wayflyer_bnpl_q4_2021', 'Level up with funding', 'https://woocommerce.com/products/wayflyer/?utm_source=inbox_note&utm_medium=product&utm_campaign=wayflyer_bnpl_q4_2021', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9687, 3, 'wc_shipping_mobile_app_usps_q4_2021', 'Get WooCommerce Shipping', 'https://woocommerce.com/woocommerce-shipping/?utm_source=inbox_note&utm_medium=product&utm_campaign=wc_shipping_mobile_app_usps_q4_2021', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9688, 5, 'learn-more', 'Learn more', 'https://woocommerce.com/posts/ecommerce-shipping-solutions-guide/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9689, 6, 'optimizing-the-checkout-flow', 'Learn more', 'https://woocommerce.com/posts/optimizing-woocommerce-checkout?utm_source=inbox_note&utm_medium=product&utm_campaign=optimizing-the-checkout-flow', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9690, 7, 'qualitative-feedback-from-new-users', 'Share feedback', 'https://automattic.survey.fm/wc-pay-new', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9691, 8, 'share-feedback', 'Share feedback', 'http://automattic.survey.fm/paypal-feedback', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9692, 9, 'get-started', 'Get started', 'https://woocommerce.com/products/google-listings-and-ads?utm_source=inbox_note&utm_medium=product&utm_campaign=get-started', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9693, 10, 'update-wc-subscriptions-3-0-15', 'View latest version', 'https://comsstore.ynetsolution.com/wp-admin/&page=wc-addons&section=helper', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9694, 11, 'update-wc-core-5-4-0', 'How to update WooCommerce', 'https://docs.woocommerce.com/document/how-to-update-woocommerce/', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9695, 14, 'ppxo-pps-install-paypal-payments-1', 'View upgrade guide', 'https://docs.woocommerce.com/document/woocommerce-paypal-payments/paypal-payments-upgrade-guide/', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9696, 15, 'ppxo-pps-install-paypal-payments-2', 'View upgrade guide', 'https://docs.woocommerce.com/document/woocommerce-paypal-payments/paypal-payments-upgrade-guide/', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9697, 16, 'learn-more', 'Learn more', 'https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9698, 16, 'dismiss', 'Dismiss', '', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9699, 17, 'learn-more', 'Learn more', 'https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9700, 17, 'dismiss', 'Dismiss', '', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9701, 18, 'learn-more', 'Learn more', 'https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9702, 18, 'dismiss', 'Dismiss', '', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9703, 19, 'learn-more', 'Learn more', 'https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=learn-more', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9704, 19, 'dismiss', 'Dismiss', '', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9705, 20, 'share-feedback', 'Share feedback', 'https://automattic.survey.fm/store-management', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9706, 21, 'learn-more', 'Learn more', 'https://developer.woocommerce.com/2022/03/10/woocommerce-3-5-10-6-3-1-security-releases/', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9707, 21, 'woocommerce-core-paypal-march-2022-dismiss', 'Dismiss', '', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9708, 22, 'learn-more', 'Learn more', 'https://developer.woocommerce.com/2022/03/10/woocommerce-3-5-10-6-3-1-security-releases/', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9709, 22, 'dismiss', 'Dismiss', '', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9710, 23, 'pinterest_03_2022_update', 'Update Instructions', 'https://woocommerce.com/document/pinterest-for-woocommerce/?utm_source=inbox_note&utm_medium=product&utm_campaign=pinterest_03_2022_update#section-3', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9711, 24, 'store_setup_survey_survey_q2_2022_share_your_thoughts', 'Tell us how it’s going', 'https://automattic.survey.fm/store-setup-survey-2022', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9712, 25, 'needs-update-eway-payment-gateway-rin-action-button-2022-12-20', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/update-core.php', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9713, 25, 'needs-update-eway-payment-gateway-rin-dismiss-button-2022-12-20', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9714, 26, 'updated-eway-payment-gateway-rin-action-button-2022-12-20', 'See all updates', 'https://comsstore.ynetsolution.com/wp-admin/update-core.php', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9715, 26, 'updated-eway-payment-gateway-rin-dismiss-button-2022-12-20', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9716, 27, 'share-navigation-survey-feedback', 'Share feedback', 'https://automattic.survey.fm/new-ecommerce-plan-navigation', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9717, 28, 'woopay-beta-merchantrecruitment-activate-04MAY23', 'Activate WooPay', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9718, 28, 'woopay-beta-merchantrecruitment-activate-learnmore-04MAY23', 'Learn More', 'https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-activate-learnmore-04MAY23', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9719, 29, 'woocommerce-wcpay-march-2023-update-needed-button', 'See Blog Post', 'https://developer.woocommerce.com/2023/03/23/critical-vulnerability-detected-in-woocommerce-payments-what-you-need-to-know', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9720, 29, 'woocommerce-wcpay-march-2023-update-needed-dismiss-button', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9721, 30, 'tap_to_pay_iphone_q2_2023_no_wcpay', 'Simplify my payments', 'https://woocommerce.com/products/woocommerce-payments/?utm_source=inbox_note&utm_medium=product&utm_campaign=tap_to_pay_iphone_q2_2023_no_wcpay', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9722, 31, 'extension-settings', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/update-core.php', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9723, 31, 'dismiss', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9724, 32, 'woopay-beta-merchantrecruitment-update-WCPay-04MAY23', 'Update WooCommerce Payments', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9725, 32, 'woopay-beta-merchantrecruitment-update-activate-04MAY23', 'Activate WooPay', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9726, 33, 'woopay-beta-existingmerchants-noaction-documentation-27APR23', 'Documentation', 'https://woocommerce.com/document/woopay-merchant-documentation/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-existingmerchants-noaction-documentation-27APR23', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9727, 34, 'woopay-beta-existingmerchants-update-WCPay-27APR23', 'Update WooCommerce Payments', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9728, 35, 'woopay-beta-merchantrecruitment-short-activate-04MAY23', 'Activate WooPay', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9729, 35, 'woopay-beta-merchantrecruitment-short-activate-learnmore-04MAY23', 'Learn More', 'https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-short-activate-learnmore-04MAY23', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9730, 36, 'woopay-beta-merchantrecruitment-short-update-WCPay-04MAY23', 'Update WooCommerce Payments', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9731, 36, 'woopay-beta-merchantrecruitment-short-update-activate-04MAY23', 'Activate WooPay', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9732, 37, 'woopay-beta-merchantrecruitment-short-activate-06MAY23-TESTA', 'Activate WooPay Test A', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9733, 37, 'woopay-beta-merchantrecruitment-short-activate-learnmore-06MAY23-TESTA', 'Learn More', 'https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-short-activate-learnmore-06MAY23-TESTA', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9734, 38, 'woopay-beta-merchantrecruitment-short-activate-06MAY23-TESTB', 'Activate WooPay Test B', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9735, 38, 'woopay-beta-merchantrecruitment-short-activate-learnmore-06MAY23-TESTA', 'Learn More', 'https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-short-activate-learnmore-06MAY23-TESTA', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9736, 39, 'woopay-beta-merchantrecruitment-short-activate-06MAY23-TESTC', 'Activate WooPay Test C', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9737, 39, 'woopay-beta-merchantrecruitment-short-activate-learnmore-06MAY23-TESTC', 'Learn More', 'https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-short-activate-learnmore-06MAY23-TESTC', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9738, 40, 'woopay-beta-merchantrecruitment-short-activate-06MAY23-TESTD', 'Activate WooPay Test D', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9739, 40, 'woopay-beta-merchantrecruitment-short-activate-learnmore-06MAY23-TESTD', 'Learn More', 'https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-short-activate-learnmore-06MAY23-TESTD', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9740, 41, 'woopay-beta-merchantrecruitment-short-activate-button-09MAY23', 'Activate WooPay', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9741, 41, 'woopay-beta-merchantrecruitment-short-activate-learnmore-button2-09MAY23', 'Learn More', 'https://woocommerce.com/woopay-businesses/?utm_source=inbox_note&utm_medium=product&utm_campaign=woopay-beta-merchantrecruitment-short-activate-learnmore-button2-09MAY23', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9742, 42, 'woopay-beta-merchantrecruitment-short-update-WCPay-09MAY23', 'Update WooCommerce Payments', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9743, 42, 'woopay-beta-merchantrecruitment-short-update-activate-09MAY23', 'Activate WooPay', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments&method=platform_checkout', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9744, 45, 'woocommerce-WCSubscriptions-June-2023-updated-needed-Plugin-Settings', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9745, 45, 'woocommerce-WCSubscriptions-June-2023-updated-needed-dismiss', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9746, 46, 'woocommerce-WCReturnsWarranty-June-2023-updated-needed', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9747, 46, 'woocommerce-WCReturnsWarranty-June-2023-updated-needed', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9748, 47, 'woocommerce-WCOPC-June-2023-updated-needed', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9749, 47, 'woocommerce-WCOPC-June-2023-updated-needed', 'Dismiss', 'https://comsstore.ynetsolution.com/wp-admin/#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9750, 48, 'woocommerce-WCGC-July-2023-update-needed', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9751, 48, 'woocommerce-WCGC-July-2023-update-needed', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9752, 49, 'learn-more', 'Learn more', 'https://woocommerce.com/document/fedex/?utm_medium=product&utm_source=inbox_note&utm_campaign=learn-more#july-2023-api-outage', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9753, 50, 'plugin-list', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php?plugin_status=all', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9754, 50, 'dismiss', 'Dismiss', 'https://comsstore.ynetsolution.com/wp-admin/admin.php?page=wc-admin', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9755, 51, 'woocommerce-WCStripe-Aug-2023-update-needed', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/update-core.php?', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9756, 51, 'dismiss', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9757, 52, 'dismiss', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9758, 54, 'dismiss', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9759, 55, 'avalara_q3-2023_noAvaTax', 'Automate my sales tax', 'https://woocommerce.com/products/woocommerce-avatax/?utm_source=inbox_note&utm_medium=product&utm_campaign=avalara_q3-2023_noAvaTax', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9760, 56, 'woo-activation-survey-blockers-survey-button-22AUG23', 'Take our short survey', 'https://woocommerce.survey.fm/getting-started-with-woo', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9761, 57, 'woocommerce-usermeta-Sept2023-productvendors', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/plugins.php', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9762, 57, 'dismiss', 'Dismiss', 'https://comsstore.ynetsolution.com/wp-admin/#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9763, 58, 'woocommerce-STRIPE-Oct-2023-update-needed', 'See available updates', 'https://comsstore.ynetsolution.com/wp-admin/update-core.php', 'unactioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9764, 58, 'dismiss', 'Dismiss', '#', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9765, 59, 'amazon-mcf-review-button-2023-12-07', 'Leave a review', 'https://woocommerce.com/products/woocommerce-amazon-fulfillment/?review&utm_source=inbox_note&utm_medium=product&utm_campaign=amazon-mcf-review-button-2023-12-07', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9766, 59, 'amazon-mcf-support-button-2023-12-07', 'Request support', 'https://woocommerce.com/my-account/contact-support/?utm_source=inbox_note&utm_medium=product&utm_campaign=amazon-mcf-support-button-2023-12-07', 'actioned', '', NULL, NULL);
INSERT INTO `wordpress`.`wp_wc_admin_note_actions` VALUES (9767, 60, 'view_docs', 'Learn about Deposit schedules', 'https://woocommerce.com/document/woopayments/deposits/deposit-schedule/?utm_source=inbox_note&utm_medium=product&utm_campaign=view_docs#available-funds', 'unactioned', '', NULL, NULL);
