CREATE TABLE IF NOT EXISTS `wordpress`.`wp_wc_order_stats`(
    `order_id` bigint unsigned NOT NULL,
    `parent_id` bigint unsigned NOT NULL DEFAULT '0',
    `date_created` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
    `date_created_gmt` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
    `date_paid` datetime NULL DEFAULT '1970-01-01 00:00:00',
    `date_completed` datetime NULL DEFAULT '1970-01-01 00:00:00',
    `num_items_sold` int NOT NULL DEFAULT '0',
    `total_sales` double NOT NULL DEFAULT '0',
    `tax_total` double NOT NULL DEFAULT '0',
    `shipping_total` double NOT NULL DEFAULT '0',
    `net_total` double NOT NULL DEFAULT '0',
    `returning_customer` tinyint(1) NULL,
    `status` varchar(200) NOT NULL,
    `customer_id` bigint unsigned NOT NULL,
    PRIMARY KEY  (`order_id` ),
    KEY `date_created` (`date_created` ),
    KEY `customer_id` (`customer_id` ),
    KEY `status` (`status`(254) )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci ;
