CREATE TABLE IF NOT EXISTS `wordpress`.`wp_wc_orders`(
    `id` bigint unsigned NOT NULL,
    `status` varchar(20) NULL,
    `currency` varchar(10) NULL,
    `type` varchar(20) NULL,
    `tax_amount` decimal(26,8) NULL,
    `total_amount` decimal(26,8) NULL,
    `customer_id` bigint unsigned NULL,
    `billing_email` varchar(320) NULL,
    `date_created_gmt` datetime NULL,
    `date_updated_gmt` datetime NULL,
    `parent_order_id` bigint unsigned NULL,
    `payment_method` varchar(100) NULL,
    `payment_method_title` text NULL,
    `transaction_id` varchar(100) NULL,
    `ip_address` varchar(100) NULL,
    `user_agent` text NULL,
    `customer_note` text NULL,
    PRIMARY KEY  (`id` ),
    KEY `status` (`status` ),
    KEY `date_created` (`date_created_gmt` ),
    KEY `customer_id_billing_email` (`customer_id` ,`billing_email`(228) ),
    KEY `billing_email` (`billing_email`(254) ),
    KEY `type_status_date` (`type` ,`status` ,`date_created_gmt` ),
    KEY `parent_order_id` (`parent_order_id` ),
    KEY `date_updated` (`date_updated_gmt` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci ;
