CREATE TABLE IF NOT EXISTS `wordpress`.`wpf0_fluentform_form_meta`(
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `form_id` int unsigned NULL,
    `meta_key` varchar(255) NOT NULL,
    `value` longtext NULL,
    PRIMARY KEY  (`id` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci ;
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (1, 1, 'template_name', 'basic_contact_form');
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (2, 1, 'formSettings', '{"confirmation":{"redirectTo":"samePage","messageToShow":"Thank you for your message. We will get in touch with you shortly","customPage":null,"samePageFormBehavior":"hide_form","customUrl":null},"restrictions":{"limitNumberOfEntries":{"enabled":false,"numberOfEntries":null,"period":"total","limitReachedMsg":"Maximum number of entries exceeded."},"scheduleForm":{"enabled":false,"start":null,"end":null,"selectedDays":["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],"pendingMsg":"Form submission is not started yet.","expiredMsg":"Form submission is now closed."},"requireLogin":{"enabled":false,"requireLoginMsg":"You must be logged in to submit the form."},"denyEmptySubmission":{"enabled":false,"message":"Sorry, you cannot submit an empty form. Let\'s hear what you wanna say."}},"layout":{"labelPlacement":"top","helpMessagePlacement":"with_label","errorMessagePlacement":"inline","cssClassName":"","asteriskPlacement":"asterisk-right"},"delete_entry_on_submission":"no","appendSurveyResult":{"enabled":false,"showLabel":false,"showCount":false}}');
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (3, 1, 'advancedValidationSettings', '{"status":false,"type":"all","conditions":[{"field":"","operator":"=","value":""}],"error_message":"","validation_type":"fail_on_condition_met"}');
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (4, 1, 'double_optin_settings', '{"status":"no","confirmation_message":"Please check your email inbox to confirm this submission","email_body_type":"global","email_subject":"Please confirm your form submission","email_body":"<h2>Please Confirm Your Submission</h2><p>&nbsp;</p><p style="text-align: center;"><a style="color: #ffffff; background-color: #454545; font-size: 16px; border-radius: 5px; text-decoration: none; font-weight: normal; font-style: normal; padding: 0.8rem 1rem; border-color: #0072ff;" href="#confirmation_url#">Confirm Submission</a></p><p>&nbsp;</p><p>If you received this email by mistake, simply delete it. Your form submission won\'t proceed if you don\'t click the confirmation link above.</p>","email_field":"","skip_if_logged_in":"yes","skip_if_fc_subscribed":"no"}');
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (5, 1, '_primary_email_field', '');
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (6, 1, '_total_views', '12');
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (7, 2, 'formSettings', '{"confirmation":{"redirectTo":"samePage","messageToShow":"Thank you for your message. We will get in touch with you shortly","customPage":null,"samePageFormBehavior":"hide_form","customUrl":null},"restrictions":{"limitNumberOfEntries":{"enabled":false,"numberOfEntries":null,"period":"total","limitReachedMsg":"Maximum number of entries exceeded."},"scheduleForm":{"enabled":false,"start":null,"end":null,"selectedDays":null,"pendingMsg":"Form submission is not started yet.","expiredMsg":"Form submission is now closed."},"requireLogin":{"enabled":false,"requireLoginMsg":"You must be logged in to submit the form."},"denyEmptySubmission":{"enabled":false,"message":"Sorry, you cannot submit an empty form. Let\'s hear what you wanna say."},"restrictForm":{"enabled":false,"fields":{"ip":{"status":false,"values":"","message":"Sorry! You can\'t submit a form from your IP address.","validation_type":"fail_on_condition_met"},"country":{"status":false,"values":[],"message":"Sorry! You can\'t submit a form the country you are residing.","validation_type":"fail_on_condition_met"},"keywords":{"status":false,"values":"","message":"Sorry! Your submission contains some restricted keywords."}}}},"layout":{"labelPlacement":"top","helpMessagePlacement":"with_label","errorMessagePlacement":"inline","cssClassName":"","asteriskPlacement":"asterisk-right"},"delete_entry_on_submission":"no"}');
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (8, 2, 'template_name', 'it_service_request_form');
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (9, 2, 'notifications', '{"name":"Admin Notification Email","sendTo":{"type":"email","email":"{wp.admin_email}","field":"email","routing":[{"email":null,"field":null,"operator":"=","value":null}]},"fromName":"","fromEmail":"","replyTo":"","bcc":"","subject":"[{inputs.names}] New Form Submission","message":"<p>{all_data}<\\/p>\\n<p>This form submitted at: {embed_post.permalink}<\\/p>","conditionals":{"status":false,"type":"all","conditions":[{"field":null,"operator":"=","value":null}]},"enabled":false,"email_template":""}');
INSERT INTO `wordpress`.`wpf0_fluentform_form_meta` VALUES (10, 2, '_primary_email_field', '');
